"""
Django settings for buildforge_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m8p371i-z$na)ox5p5=$=_$**ald*gbd994^+bfk-)oi@j5ae%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #_____________________________________________________________________________________________________________________ (akn)

    # Third-party apps
    'django_htmx',

    # My apps
    'users.apps.UsersConfig',
    'catalog.apps.CatalogConfig',
    'builds.apps.BuildsConfig',
    'marketplace.apps.MarketplaceConfig',

    #_____________________________________________________________________________________________________________________
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'buildforge_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #_________________________________________________________________________________________________________________ (akn)

        'DIRS': [os.path.join(BASE_DIR, 'templates')], # telling Django where to find project-wide templates.
        #_________________________________________________________________________________________________________________
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'buildforge_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#____________________________________________________________________________________________________________________________ Connecting Django to the database (akn)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'buildforge_db',   # The database name you created
        'USER': 'root',             # Default XAMPP user
        'PASSWORD': '',              # Default XAMPP password (empty)
        'HOST': '127.0.0.1',        # Or 'localhost'
        'PORT': '3306',             # Default MySQL port
        'OPTIONS': { # The OPTIONS part is important to prevent common errors with modern versions of MySQL.
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
#____________________________________________________________________________________________________________________________

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#____________________________________________________________________________________________________________________________ (akn)

# Media files (user-uploaded content) configuration
# This is the URL that will serve the media files.
MEDIA_URL = '/media/'

# This is the absolute path to the directory where media files will be stored.
# os.path.join(BASE_DIR, 'media') creates a folder named 'media' in your project's root directory.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Tell Django to use our CustomUser model for authentication (every ForeignKey to a user will correctly point to your CustomUser table)
AUTH_USER_MODEL = 'users.CustomUser'

# tell Django where to send users after they log in or log out.
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
#____________________________________________________________________________________________________________________________