# Generated by Django 4.2.26 on 2025-12-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builds', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildcomponent',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.build'),
        ),
        migrations.AddField(
            model_name='buildcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.component'),
        ),
        migrations.AddField(
            model_name='build',
            name='components',
            field=models.ManyToManyField(through='builds.BuildComponent', to='catalog.component'),
        ),
        migrations.AddField(
            model_name='build',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='buildcomponent',
            unique_together={('build', 'component')},
        ),
    ]
