# Generated by Django 5.2.9 on 2025-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
