# Generated by Django 6.0 on 2025-12-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_marketplacelisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Phone number, email, or other contact details.', max_length=255),
        ),
    ]
