# marketplace/admin.py

#__________________________________________________________________________________________________________________________ (akn)

from django.contrib import admin
from .models import MarketplaceListing

admin.site.register(MarketplaceListing)

#__________________________________________________________________________________________________________________________