# Generated by Django 4.2.26 on 2025-12-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('manufacturer', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, max_length=1500, null=True, upload_to='components/')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='Thermal Design Power in Watts', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performance_tier', models.CharField(blank=True, choices=[('Entry', 'Entry-Level'), ('Mid', 'Mid-Range'), ('High', 'High-End')], help_text='Performance tier for bottleneck calculations (primarily for CPU/GPU)', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=20)),
                ('max_gpu_length', models.CharField(blank=True, help_text='Maximum GPU length in mm', max_length=5, null=True)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('core_count', models.PositiveIntegerField()),
                ('clock_speed', models.CharField(help_text='Clock speed in GHz', max_length=30)),
                ('socket', models.CharField(max_length=50)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('vram_gb', models.CharField(help_text='VRAM in Gigabytes', max_length=7)),
                ('gpu_clock_speed', models.CharField(help_text='Clock speed in MHz', max_length=20)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('socket', models.CharField(max_length=50)),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=20)),
                ('ram_slots', models.PositiveIntegerField()),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('wattage', models.CharField(help_text='Wattage in Watts', max_length=5)),
                ('efficiency_rating', models.CharField(choices=[('80+', '80+'), ('Bronze', '80+ Bronze'), ('Silver', '80+ Silver'), ('Gold', '80+ Gold'), ('Platinum', '80+ Platinum'), ('Titanium', '80+ Titanium')], max_length=20)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('capacity_gb', models.CharField(help_text='Capacity per stick in Gigabytes', max_length=20)),
                ('speed_mhz', models.CharField(help_text='Speed in MHz', max_length=20)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('capacity_gb', models.CharField(help_text='Capacity in Gigabytes', max_length=10)),
                ('storage_type', models.CharField(choices=[('SSD', 'Solid State Drive'), ('NVMe', 'NVMe SSD'), ('HDD', 'Hard Disk Drive')], max_length=10)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.component')),
            ],
        ),
    ]
