# Generated by Django 4.2.26 on 2025-12-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='Thermal Design Power in Watts', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=20)),
                ('max_gpu_length', models.PositiveIntegerField(blank=True, help_text='Maximum GPU length in mm', null=True)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('core_count', models.PositiveIntegerField()),
                ('clock_speed', models.DecimalField(decimal_places=2, help_text='Clock speed in GHz', max_digits=4)),
                ('socket', models.CharField(max_length=50)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('vram_gb', models.PositiveIntegerField(help_text='VRAM in Gigabytes')),
                ('gpu_clock_speed', models.DecimalField(decimal_places=2, help_text='Clock speed in MHz', max_digits=5)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('socket', models.CharField(max_length=50)),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=20)),
                ('ram_slots', models.PositiveIntegerField()),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('wattage', models.PositiveIntegerField(help_text='Wattage in Watts')),
                ('efficiency_rating', models.CharField(choices=[('80+', '80+'), ('Bronze', '80+ Bronze'), ('Silver', '80+ Silver'), ('Gold', '80+ Gold'), ('Platinum', '80+ Platinum'), ('Titanium', '80+ Titanium')], max_length=20)),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('capacity_gb', models.PositiveIntegerField(help_text='Capacity per stick in Gigabytes')),
                ('speed_mhz', models.PositiveIntegerField(help_text='Speed in MHz')),
            ],
            bases=('catalog.component',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.component')),
                ('capacity_gb', models.PositiveIntegerField(help_text='Capacity in Gigabytes')),
                ('storage_type', models.CharField(choices=[('SSD', 'Solid State Drive'), ('NVMe', 'NVMe SSD'), ('HDD', 'Hard Disk Drive')], max_length=10)),
            ],
            bases=('catalog.component',),
        ),
    ]
