# Generated by Django 4.2.26 on 2025-12-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
