# Generated by Django 4.2.26 on 2025-12-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='gpu_clock_speed',
            field=models.DecimalField(decimal_places=2, help_text='Clock speed in MHz', max_digits=7),
        ),
    ]
