# Generated by Django 4.2.26 on 2025-12-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_gpu_gpu_clock_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='performance_tier',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry-Level'), ('Mid', 'Mid-Range'), ('High', 'High-End')], help_text='Performance tier for bottleneck calculations (primarily for CPU/GPU)', max_length=10, null=True),
        ),
    ]
