# Generated by Django 4.2.26 on 2025-12-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_component_performance_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='components/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
