# Generated by Django 4.2.26 on 2025-12-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_component_image_alter_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='max_gpu_length',
            field=models.CharField(blank=True, help_text='Maximum GPU length in mm', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='clock_speed',
            field=models.CharField(help_text='Clock speed in GHz', max_length=30),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='gpu_clock_speed',
            field=models.CharField(help_text='Clock speed in MHz', max_length=7),
        ),
        migrations.AlterField(
            model_name='psu',
            name='wattage',
            field=models.CharField(help_text='Wattage in Watts', max_length=5),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity_gb',
            field=models.CharField(help_text='Capacity per stick in Gigabytes', max_length=20),
        ),
        migrations.AlterField(
            model_name='ram',
            name='speed_mhz',
            field=models.CharField(help_text='Speed in MHz', max_length=20),
        ),
    ]
