# Generated by Django 4.2.26 on 2025-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_case_max_gpu_length_alter_cpu_clock_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='vram_gb',
            field=models.CharField(help_text='VRAM in Gigabytes', max_length=7),
        ),
    ]
