# Generated by Django 4.2.26 on 2025-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_gpu_vram_gb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='gpu_clock_speed',
            field=models.CharField(help_text='Clock speed in MHz', max_length=20),
        ),
    ]
