# Generated by Django 4.2.26 on 2025-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_gpu_gpu_clock_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='capacity_gb',
            field=models.CharField(help_text='Capacity in Gigabytes', max_length=10),
        ),
    ]
